### PR TITLE
Added FayasNoushad

### PR DESCRIPTION
**Pull request by FayasNoushad**

### CODE REVIEW

**Comment by FayasNoushad** [comment]
How to merge? I can't merge this. I am a team member.

**Review by AvidCoder101 — APPROVED** [review]
LGTM, thanks for contributing (:

**Comment by VasudevJaiswal** [comment]
> How to merge? I can't merge this. I am a team member.

https://github.com/orgs/Jaidevstudio/teams/support

**Comment by CodingSpecies** [comment]
@all-contributors please add @FayasNoushad  for content

**Comment by CodingSpecies** [comment]
@all-contributors please add @FayasNoushad  for content

**Pull request merged**
