### PR TITLE
Added AvidCoder's profile

### LINKED ISSUE #5: Avid Coder's Profile
image

### PR DESCRIPTION
**Pull request by AvidCoder101**
resolves #5

### CODE REVIEW

**Comment by CodingSpecies** [comment]
LGTM! Thank you for contributing.

**Review by CodingSpecies — APPROVED** [review]

**Comment by AvidCoder101** [comment]
Could I please join the organization?

**Comment by CodingSpecies** [comment]
@all-contributors please add @AvidCoder101  for content

**Comment by CodingSpecies** [comment]
@all-contributors please add @AvidCoder101 for content

**Pull request merged**
